version: '3.2'
networks:
  app-tier:
    driver: bridge
services:
  clickhouse:
    image: 'yandex/clickhouse-server:20.5.5.74'
    networks:
      - app-tier
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9009:9009'
    volumes:
      - type: bind
        source: ./init-test-db.sql
        target: /docker-entrypoint-initdb.d/init-test-db.sql